-- Add missing columns to orders table for checkout functionality

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS order_number TEXT UNIQUE NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS subtotal NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS shipping NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS full_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS shipping_address JSONB DEFAULT '{"line1":"","line2":"","city":"","state":"","zip":"","phone":""}'::JSONB,
ADD COLUMN IF NOT EXISTS items JSONB DEFAULT '[]'::JSONB;
